### ISSUE TITLE
osfamily vs operatingsystem in params

### ISSUE THREAD

**Issue by Cinderhaze** [puppet-community/puppet-jira#88]
On an amazon AMI, $::osfamily is RedHat, but $::operatingsystem is Amazon.  the problem is that the $::operatingsystemmajrelease is 2015, when the conditional only looks to see if it is 6 or 7.  This results in no 'default' option under RedHat.

The correct defaults for the Amazon AMI are the same as RedHat 6 

I'm not sure what the best fix would be... switching to $::operatingsystem instead of $::osfamily and adding an /Amazon/ match, or adding an extra conditional inside of the /RedHat/ $::osfamily.

**Comment by mkrakowitzer** [comment]
Switching to $::operatingsystem would mean you would need to cater for other Redhat variants such as Centos and Scientific, although it would probably read better.  Would you be happy to submit a patch for above? I am happy with either option.

**Comment by Cinderhaze** [comment]
Sure!  I ran into an issue with the same thing before using the elasticsearch module
https://github.com/elastic/puppet-elasticsearch/blob/master/manifests/params.pp

I'll do something similar to the service parameters section

**Comment by Cinderhaze** [comment]
My PR was merged, closing...
https://github.com/puppet-community/puppet-jira/pull/89
