### ISSUE TITLE
SSL does not work with proxy

### ISSUE THREAD

**Issue by oysteing** [puppet-community/puppet-jira#90]
When using SSL and proxy together, Tomcat fails on startup with
> SEVERE: Parse Fatal Error at line 75 column 35: Attribute "scheme" was already specified for element "Connector".

Example declaration:
```
  class { '::jira':
    javahome           => $profile::java::java_home,
    tomcatNativeSsl    => true,
    proxy              => {
      scheme    => 'https',
      proxyPort => '443',
      proxyName => 'jira.example.org',
    }
  }
```

The server.xml.erb template should not add scheme twice in this case.

**Comment by mkrakowitzer** [comment]
Thanks for the patch.
